<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Security_Word</name>
   <tag></tag>
   <elementGuidId>4e8a7cde-5484-40c6-a6fd-17fa70646c7e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='securityAnswerControl']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#securityAnswerControl</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Answer to your security question&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>24776bf9-e09f-4954-b339-04e9210a5614</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>securityAnswerControl</value>
      <webElementGuid>608c88b9-cfee-4210-bfbe-808b540de399</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ae24e0e9-08bb-40e5-883b-326516fcf9fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Field for the answer to the security question</value>
      <webElementGuid>42f367f0-ac9a-4f48-ad8a-f86c88d0e3dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-input-element mat-form-field-autofill-control ng-tns-c21-18 ng-untouched ng-pristine ng-invalid cdk-text-field-autofill-monitored</value>
      <webElementGuid>a81d567d-9832-4fa0-8c32-df45b16cbeb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Answer to your security question</value>
      <webElementGuid>42ff2217-31bc-492b-b80f-f011c229ce8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placeholder</name>
      <type>Main</type>
      <value>Answer to your security question</value>
      <webElementGuid>42bf3a1d-0aee-4bab-ab85-aeab48d0b48b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>dbf5b30f-f6b6-45e9-bb6d-6f6106e6782d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;securityAnswerControl&quot;)</value>
      <webElementGuid>5f2f6440-021f-480d-abb9-6a8b71eada1a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='securityAnswerControl']</value>
      <webElementGuid>dfc7a62a-0634-49db-a9f5-9f25a9232d40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='registration-form']/div/mat-form-field[2]/div/div/div[3]/input</value>
      <webElementGuid>32076b43-6e0b-4095-9c09-922ea62c0dfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/mat-form-field[2]/div/div/div[3]/input</value>
      <webElementGuid>d5cee1c6-3aa5-4871-90f5-bbbc0bb6db5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'securityAnswerControl' and @type = 'text' and @placeholder = 'Answer to your security question']</value>
      <webElementGuid>84e3d330-e17c-4547-b88a-ec0439c7b6d2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
