<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mat-Error_Passwords</name>
   <tag></tag>
   <elementGuidId>4f1cfbd7-f39d-48ad-8f98-358e05a2b708</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//mat-error[@id='mat-error-10']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mat-error-10</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Passwords do not match&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-error</value>
      <webElementGuid>cd4e2e61-9dd5-43cc-bd51-5e2abbf6e181</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-atomic</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ca9d67f5-f44e-4497-8df1-39006a43a9ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-error ng-tns-c21-15 ng-star-inserted</value>
      <webElementGuid>ac014e56-cebd-40a2-9a40-1ac667784798</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-live</name>
      <type>Main</type>
      <value>polite</value>
      <webElementGuid>5cd7881e-28d0-414e-8058-cc464821547e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-error-10</value>
      <webElementGuid>786b2df2-f7c4-4433-ada6-4ebf1ab6ae59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Passwords do not match </value>
      <webElementGuid>6cfe95d5-93d7-4a3c-bf3d-ae7be19c264b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-error-10&quot;)</value>
      <webElementGuid>802ce0ae-e19c-4c21-b87b-3d20e99869bd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//mat-error[@id='mat-error-10']</value>
      <webElementGuid>e66cee98-36c6-4c6c-8c08-e503a492481e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='registration-form']/mat-form-field[3]/div/div[2]/div/mat-error</value>
      <webElementGuid>928a2d25-3c26-4899-8c7d-1eef86387894</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Repeat Password'])[1]/following::mat-error[1]</value>
      <webElementGuid>20b66d32-7ab3-4d24-962b-d0033f983f90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password must be 5-40 characters long.'])[1]/following::mat-error[1]</value>
      <webElementGuid>d08ccfeb-b0d7-4e00-a3a5-733e94502fb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Security Question'])[1]/preceding::mat-error[1]</value>
      <webElementGuid>6d43b8a6-140b-4e2e-8980-b9a77ecfeb84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Passwords do not match']/parent::*</value>
      <webElementGuid>8fa1cefb-14f1-423d-a1e0-a6f5461e5782</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-error</value>
      <webElementGuid>e2dc2b02-0615-4809-9e5a-2f2408657b31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-error[@id = 'mat-error-10' and (text() = ' Passwords do not match ' or . = ' Passwords do not match ')]</value>
      <webElementGuid>8a78f737-b5c4-4477-b22a-6154ecd0dba5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
